// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace XamWalletDemo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27");

            modelBuilder.Entity("XamWalletDemo.MemberInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberID")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RxBinNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemberInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
